//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define ICM_NOTOPEN                     0x0000
#define EPR_0                           0
#define CTFMODEBIAS_DEFAULT             0x0000
#define EMO_EXIT                        0
#define EMO_EXPANDSELECTION             0
#define ENM_NONE                        0x00000000
#define CFU_UNDERLINENONE               0
#define SCF_DEFAULT                     0x0000
#define PFNS_PAREN                      0x000
#define SEL_EMPTY                       0x0000
#define ST_DEFAULT                      0
#define GT_DEFAULT                      0
#define GTL_DEFAULT                     0
#define SES_EMULATESYSEDIT              1
#define IMF_AUTOKEYBOARD                0x0001
#define ICM_LEVEL3                      0x0001
#define TO_ADVANCEDTYPOGRAPHY           1
#define EPR_270                         1
#define CTFMODEBIAS_FILENAME            0x0001
#define IMF_SMODE_PLAURALCLAUSE         0x0001
#define ICT_RESULTREADSTR               1
#define EMO_ENTER                       1
#define EMO_EXPANDDOCUMENT              1
#define ENM_CHANGE                      0x00000001
#define ECO_AUTOWORDSELECTION           0x00000001
#define ECOOP_SET                       0x0001
#define PC_FOLLOWING                    1
#define IMF_FORCENONE                   0x0001
#define CFM_BOLD                        0x00000001
#define CFE_BOLD                        0x0001
#define CFU_UNDERLINE                   1
#define SCF_SELECTION                   0x0001
#define SF_TEXT                         0x0001
#define PFM_STARTINDENT                 0x00000001
#define PFN_BULLET                      1
#define PFA_LEFT                        1
#define SEL_TEXT                        0x0001
#define OLEOP_DOVERB                    1
#define ST_KEEPUNDO                     1
#define GT_USECRLF                      1
#define GTL_USECRLF                     1
#define SES_BEEPONMAXTEXT               2
#define IMF_AUTOFONT                    0x0002
#define ICM_LEVEL2                      0x0002
#define TO_SIMPLELINEBREAK              2
#define EPR_180                         2
#define CTFMODEBIAS_NAME                0x0002
#define IMF_SMODE_NONE                  0x0002
#define EMO_PROMOTE                     2
#define VM_OUTLINE                      2
#define ENM_UPDATE                      0x00000002
#define ECOOP_OR                        0x0002
#define PC_LEADING                      2
#define IMF_FORCEENABLE                 0x0002
#define CFM_ITALIC                      0x00000002
#define CFE_ITALIC                      0x0002
#define CFU_UNDERLINEWORD               2
#define SCF_WORD                        0x0002
#define SF_RTF                          0x0002
#define PFM_RIGHTINDENT                 0x00000002
#define PFN_ARABIC                      2
#define PFA_RIGHT                       2
#define SEL_OBJECT                      0x0002
#define ST_SELECTION                    2
#define GT_SELECTION                    2
#define GTL_PRECISE                     2
#define ICM_LEVEL2_5                    0x0003
#define EPR_90                          3
#define CTFMODEBIAS_READING             0x0003
#define EMO_EXPAND                      3
#define ECOOP_AND                       0x0003
#define WB_CLASSIFY                     3
#define PC_OVERFLOW                     3
#define CFU_UNDERLINEDOUBLE             3
#define SF_RTFNOOBJS                    0x0003
#define PFN_LCLETTER                    3
#define PFA_CENTER                      3
#define SES_EXTENDBACKCOLOR             4
#define IMF_IMECANCELCOMPLETE           0x0004
#define ICM_LEVEL2_SUI                  0x0004
#define TO_DISABLECUSTOMTEXTOUT         4
#define CTFMODEBIAS_DATETIME            0x0004
#define EMO_MOVESELECTION               4
#define VM_NORMAL                       4
#define ENM_SCROLL                      0x00000004
#define ECOOP_XOR                       0x0004
#define WB_MOVEWORDLEFT                 4
#define WB_MOVEWORDPREV                 4
#define PC_DELIMITER                    4
#define IMF_FORCEDISABLE                0x0004
#define CFM_UNDERLINE                   0x00000004
#define CFE_UNDERLINE                   0x0004
#define CFU_UNDERLINEDOTTED             4
#define SCF_ALL                         0x0004
#define SF_TEXTIZED                     0x0004
#define PFM_OFFSET                      0x00000004
#define PFN_UCLETTER                    4
#define PFA_JUSTIFY                     4
#define PFA_FULL_INTERWORD              4
#define SEL_MULTICHAR                   0x0004
#define ST_NEWCHARS                     4
#define GT_RAWTEXT                      4
#define GTL_CLOSE                       4
#define BOM_NEUTRALOVERRIDE             0x0004
#define BOE_NEUTRALOVERRIDE             0x0004
#define ICM_CTF                         0x0005
#define CTFMODEBIAS_CONVERSATION        0x0005
#define EMO_GETVIEWMODE                 5
#define WB_MOVEWORDRIGHT                5
#define WB_MOVEWORDNEXT                 5
#define CFU_UNDERLINEDASH               5
#define PFN_LCROMAN                     5
#define PFA_FULL_INTERLETTER            5
#define CTFMODEBIAS_NUMERIC             0x0006
#define WB_LEFTBREAK                    6
#define WB_PREVBREAK                    6
#define CFU_UNDERLINEDASHDOT            6
#define PFN_UCROMAN                     6
#define PFA_FULL_SCALED                 6
#define CTFMODEBIAS_HIRAGANA            0x0007
#define WB_RIGHTBREAK                   7
#define WB_NEXTBREAK                    7
#define CFU_UNDERLINEDASHDOTDOT         7
#define PFA_FULL_GLYPHS                 7
#define SES_MAPCPS                      8
#define IMF_IMEALWAYSSENDNOTIFY         0x0008
#define TO_ADVANCEDLAYOUT               8
#define CTFMODEBIAS_KATAKANA            0x0008
#define ENM_SCROLLEVENTS                0x00000008
#define ES_NOOLEDRAGDROP                0x00000008
#define IMF_CLOSESTATUSWINDOW           0x0008
#define CFM_STRIKEOUT                   0x00000008
#define CFE_STRIKEOUT                   0x0008
#define CFU_UNDERLINEWAVE               8
#define SCF_USEUIRULES                  0x0008
#define PFM_ALIGNMENT                   0x00000008
#define PFA_SNAP_GRID                   8
#define SEL_MULTIOBJECT                 0x0008
#define GT_NOHIDDENTEXT                 8
#define GTL_NUMCHARS                    8
#define BOM_CONTEXTREADING              0x0008
#define BOE_CONTEXTREADING              0x0008
#define CTFMODEBIAS_HANGUL              0x0009
#define VM_PAGE                         9
#define CFU_UNDERLINETHICK              9
#define CTFMODEBIAS_HALFWIDTHKATAKANA   0x000A
#define CFU_UNDERLINEHAIRLINE           10
#define CTFMODEBIAS_FULLWIDTHALPHANUMERIC 0x000B
#define CFU_UNDERLINEDOUBLEWAVE         11
#define CTFMODEBIAS_HALFWIDTHALPHANUMERIC 0x000C
#define CFU_UNDERLINEHEAVYWAVE          12
#define CFU_UNDERLINELONGDASH           13
#define CFU_UNDERLINETHICKDASH          14
#define CFU_UNDERLINETHICKDASHDOT       15
#define SES_EMULATE10                   16
#define IMF_AUTOFONTSIZEADJUST          0x0010
#define ENM_DRAGDROPDONE                0x00000010
#define WBF_WORDWRAP                    0x010
#define CFM_PROTECTED                   0x00000010
#define CFE_PROTECTED                   0x0010
#define CFU_UNDERLINETHICKDASHDOTDOT    16
#define SCF_ASSOCIATEFONT               0x0010
#define SF_UNICODE                      0x0010
#define PFM_TABSTOPS                    0x00000010
#define GTL_NUMBYTES                    16
#define BOM_CONTEXTALIGNMENT            0x0010
#define BOE_CONTEXTALIGNMENT            0x0010
#define CFU_UNDERLINETHICKDOTTED        17
#define CFU_UNDERLINETHICKLONGDASH      18
#define SES_USECRLF                     32
#define IMF_UIFONTS                     0x0020
#define ENM_PARAGRAPHEXPANDED           0x00000020
#define WBF_WORDBREAK                   0x020
#define IMF_VERTICAL                    0x0020
#define CFM_LINK                        0x00000020
#define CFE_LINK                        0x0020
#define SCF_NOKBUPDATE                  0x0020
#define SF_USECODEPAGE                  0x0020
#define MAX_TAB_STOPS                   32
#define PFM_NUMBERING                   0x00000020
#define MAX_TABLE_CELLS                 63
#define SES_USEAIMM                     64
#define ENM_PAGECHANGE                  0x00000040
#define ECO_AUTOVSCROLL                 0x00000040
#define WBF_OVERFLOW                    0x040
#define IMF_FORCEACTIVE                 0x0040
#define CFM_SMALLCAPS                   0x0040
#define SCF_ASSOCIATEFONT2              0x0040
#define SF_NCRFORNONASCII               0x40
#define PFM_SPACEBEFORE                 0x00000040
#define WM_NOTIFY                       0x004E
#define IDD_MAIN                        102
#define IDI_COMP                        103
#define IDI_OFFLINE                     104
#define IDI_ONLINE                      105
#define IDI_NOTICK                      106
#define IDI_URL                         107
#define IDI_FILE                        108
#define IDI_HISTORY                     109
#define IDI_MSG                         110
#define IDI_TICK                        111
#define IDR_MAINMENU                    112
#define IDR_CONTEXTMENU                 113
#define IDD_HISTORYEDIT                 114
#define IDI_AUTH                        115
#define IDI_ADD                         116
#define WM_CONTEXTMENU                  0x007B
#define SES_NOIME                       128
#define IMF_DUALFONT                    0x0080
#define ECO_AUTOHSCROLL                 0x00000080
#define WBF_LEVEL1                      0x080
#define IMF_FORCEINACTIVE               0x0080
#define CFM_ALLCAPS                     0x0080
#define SFF_WRITEXTRAPAR                0x80
#define PFM_SPACEAFTER                  0x00000080
#define CFU_INVERT                      0xFE
#define CFU_CF1UNDERLINE                0xFF
#define SES_ALLOWBEEPS                  256
#define ECO_NOHIDESEL                   0x00000100
#define WBF_LEVEL2                      0x100
#define IMF_FORCEREMEMBER               0x0100
#define CFM_HIDDEN                      0x0100
#define PFM_LINESPACING                 0x00000100
#define PFNS_PARENS                     0x100
#define WM_UNICHAR                      0x0109
#define SES_UPPERCASE                   512
#define WBF_CUSTOM                      0x200
#define CFM_OUTLINE                     0x0200
#define PFNS_PERIOD                     0x200
#define lDefaultTab                     720
#define _RICHEDIT_VER                   0x0300
#define PFNS_PLAIN                      0x300
#define WM_PRINTCLIENT                  0x0318
#define IDC_EDIT1                       1000
#define IDC_HISTORY                     1001
#define IDC_CHECK1                      1001
#define IDC_RICHEDIT21                  1002
#define SES_LOWERCASE                   1024
#define IMF_MULTIPLEEDIT                0x0400
#define CFM_SHADOW                      0x0400
#define PFM_STYLE                       0x00000400
#define PFNS_NONUMBER                   0x400
#define yHeightCharPtsMost              1638
#define EN_MSGFILTER                    0x0700
#define SF_RTFVAL                       0x0700
#define EN_REQUESTRESIZE                0x0701
#define EN_SELCHANGE                    0x0702
#define EN_DROPFILES                    0x0703
#define EN_PROTECTED                    0x0704
#define EN_CORRECTTEXT                  0x0705
#define EN_STOPNOUNDO                   0x0706
#define EN_IMECHANGE                    0x0707
#define EN_SAVECLIPBOARD                0x0708
#define EN_OLEOPFAILED                  0x0709
#define EN_OBJECTPOSITIONS              0x070a
#define EN_LINK                         0x070b
#define EN_DRAGDROPDONE                 0x070c
#define EN_PARAGRAPHEXPANDED            0x070d
#define EN_PAGECHANGE                   0x070e
#define EN_LOWFIRTF                     0x070f
#define EN_ALIGNLTR                     0x0710
#define EN_ALIGNRTL                     0x0711
#define SES_NOINPUTSEQUENCECHK          2048
#define ECO_READONLY                    0x00000800
#define CFM_EMBOSS                      0x0800
#define SFF_PWD                         0x0800
#define PFM_BORDER                      0x00000800
#define SES_BIDI                        4096
#define ECO_WANTRETURN                  0x00001000
#define CFM_IMPRINT                     0x1000
#define SFF_KEEPDOCINFO                 0x1000
#define PFM_SHADING                     0x00001000
#define SES_SCROLLONKILLFOCUS           8192
#define ES_DISABLENOSCROLL              0x00002000
#define CFM_DISABLED                    0x2000
#define SFF_PERSISTVIEWSCALE            0x2000
#define PFM_NUMBERINGSTYLE              0x00002000
#define SES_XLTCRCRLFTOCR               16384
#define ES_SUNKEN                       0x00004000
#define CFM_REVISED                     0x4000
#define SFF_PLAINRTF                    0x4000
#define PFM_NUMBERINGTAB                0x00004000
#define cchTextLimitDefault             32767
#define SES_DRAFTMODE                   32768
#define ES_SAVESEL                      0x00008000
#define ECO_SAVESEL                     0x00008000
#define CFM_REVAUTHOR                   0x00008000
#define SFF_SELECTION                   0x8000
#define PFM_NUMBERINGSTART              0x00008000
#define PFNS_NEWNUMBER                  0x8000
#define GCM_RIGHTMOUSEDROP              0x8000
#define MENU_REFRESH_CONTACTS           40001
#define MENU_REFRESH_HISTORY            40002
#define MENU_EXIT                       40003
#define MENU_DELETE_ITEM                40004
#define MENU_EDIT_ITEM                  40005
#define MENU_CLEAR_CONTACT              40007
#define MENU_EXPORT2XML                 40008
#define MENU_EXPORT2TXT                 40009
#define v                               40010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40011
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
